# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e7e0b48c0a12527746e35ec0b05558d5c478ba2f4b137d463fe11be56baa975b870b4fcfa17c6e485552f909f489739739b10fb9e04fccdad5d63764060935c

test:
  secret_key_base: 7dad6d68070aa7c5ac0062a8ed640a968b184273212c5f10db8d2d0e3a8d7e501e357a06ebbbb660c6f85acb0150f31f9aa5142be1cee94fe9e1b139bfe798ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
